version: '3.7'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    environment:
      ZOO_PORT_NUMBER: 2181
      ZOO_TICK_TIME: 2000
      ZOO_ENABLE_AUTH: yes
    volumes:
      - $HOME/PlayGround/docker_container_volumes/zookeeper:/bitnami/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:3.4.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - $HOME/PlayGround/docker_container_volumes/kafka:/bitnami/kafka